spring.application.name=english-learning
# =====================
# SERVER
# =====================
server.port=${PORT:8080}
# XÓA DÒNG NÀY (?ã gây crash)
# server.address=localhost
# =====================
# SWAGGER
# =====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# =====================
# DATABASE (RAILWAY)
# =====================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# =====================
# JWT
# =====================
jwt.secret=9f73cf8d7e6d79dca4992fcd8b0c86b7be2cf1331f289ae14b96c2db987123bc
# =====================
# MAIL
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587 
spring.mail.username=gay2k4@gmail.com
spring.mail.password=xncg vqtd jfzc nntz
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true
# =====================
# REDIS (COMMENT VÌ KHÔNG DÙNG TRÊN RAILWAY)
# =====================
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
